#!/usr/bin/env sh

yabai=/opt/homebrew/bin/yabai
jq=/opt/homebrew/bin/jq

SPACESLIST=($($yabai --message query --spaces | $jq --raw-output '.[] .label'))
CURRENTSPACENAME=$($yabai --message query --spaces --space | $jq --raw-output '.label')
echo "${SPACESLIST[@]}@$CURRENTSPACENAME"
